# Generated by Django 3.1.2 on 2020-10-08 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20201008_0629'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
