# Generated by Django 3.1.2 on 2020-10-08 06:34

import ckeditor.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_delete_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('body', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('blog_image', models.ImageField(default='', upload_to='blognew/image')),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('category', models.ManyToManyField(default='coding', to='blog.Category')),
            ],
        ),
    ]
